### ISSUE TITLE
Is this library going to be available?

### ISSUE THREAD

**Issue by NothinRandom** [legion2k/pyOPCDAClient#1]
I'm looking for a OPC-XML-DA client library.  I'm not sure if yours is OPC-XML-DA or OPC-DA.

**Comment by legion2k** [comment]
> 
Uploded

**Comment by NothinRandom** [comment]
@legion2k Thanks!  I'm somewhat bummed out since I need to read OPC-XML-DA in Python3x.  I started writing library for it, but definitely still early WIP.  With this in mind, I'll close it out.  Thanks for your work on this repo!
